version: '3'

services:
  db:
    container_name: todosdb
    hostname: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tduser
      POSTGRES_PASSWORD: tdpass
      POSTGRES_DB: todos

  app:
    image: realbucksavage/todos
    container_name: todosapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      GIN_MODE: release

volumes:
  postgres_data:
